//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GameApiEntities : DbContext
    {
        public GameApiEntities()
            : base("name=GameApiEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameStatu> GameStatus { get; set; }
        public virtual DbSet<PlayerInGameStatu> PlayerInGameStatus { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Statement> Statements { get; set; }
    }
}
